apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v3rxgafql-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v3rxgafql-nodejs 
  name: v3rxgafql-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: v3rxgafql-nodejs 
